# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73ff43d0b13f1b5cd69cb92e483a72f90684a92bb015396d2c97226bd09898fa3eb7199f1c51ef16d589dfbe0f2c69200ee6b6f4448b6940ee231b7003fe3e63

test:
  secret_key_base: 2d6beabddfe20a07b2033f135097faac3a3ff90c8dd48700107b9201260c3fb8577e0002d6420d6a6cc9527fb90723f81433dac6a4b05745c51023741b2c7ce4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
